### ISSUE TITLE
Update images to be current people.

### ISSUE THREAD

**Issue by yu-nix** [HackGT/hexlabs-website#28]
Images can be found in the Photos shared drive.

The aim of this task is to swap out the images with more up to date images with people we recognize.

**Comment by PhillipPhanhthourath** [comment]
@husnajakeer Notice the image in the get involved box is not loading (via hexlabs.org). I think you are using how-to-get-involved.jpg (which is having trouble loading in github) instead of get-involved-new.JPG in the get-involved.tsx file. Please make this fix as soon as you can 🙏
